server:
  port: 8082
spring:
  application:
    name: product-app
  cache:
    type: none
  jpa:
    hibernate:
      ddl-auto: updater

      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


j2cache:
  config-location: classpath:/j2cache.properties
  open-spring-cache: true
  redis-client:  jedis

