// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Group.proto

package org.smart.website.commons.lib;

public final class GroupProto {
  private GroupProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderToGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderToGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderGetGroupReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderGetGroupReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Group.proto\"8\n\023OrderToGroupRequest\022\016\n\006" +
      "userId\030\001 \001(\t\022\021\n\tproductId\030\002 \001(\t\"M\n\022Order" +
      "GetGroupReply\022\017\n\007GroupId\030\001 \001(\t\022\023\n\013GroupA" +
      "mount\030\002 \001(\t\022\021\n\tGroupName\030\003 \001(\t2V\n\024OrderG" +
      "etGroupMessage\022>\n\017GetOrderToGroup\022\024.Orde" +
      "rToGroupRequest\032\023.OrderGetGroupReply\"\000B-" +
      "\n\035com.smart.website.commons.libB\nGroupPr" +
      "otoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OrderToGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderToGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderToGroupRequest_descriptor,
        new java.lang.String[] { "UserId", "ProductId", });
    internal_static_OrderGetGroupReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OrderGetGroupReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderGetGroupReply_descriptor,
        new java.lang.String[] { "GroupId", "GroupAmount", "GroupName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
