// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Promotion.proto

package org.smart.website.commons.lib;

public interface OrderGetPromotionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderGetPromotionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string PromotionId = 1;</code>
   */
  java.lang.String getPromotionId();
  /**
   * <code>string PromotionId = 1;</code>
   */
  com.google.protobuf.ByteString
      getPromotionIdBytes();

  /**
   * <code>string PromotionAmount = 2;</code>
   */
  java.lang.String getPromotionAmount();
  /**
   * <code>string PromotionAmount = 2;</code>
   */
  com.google.protobuf.ByteString
      getPromotionAmountBytes();

  /**
   * <code>string PromotionName = 3;</code>
   */
  java.lang.String getPromotionName();
  /**
   * <code>string PromotionName = 3;</code>
   */
  com.google.protobuf.ByteString
      getPromotionNameBytes();
}
