// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RedPacket.proto

package org.smart.website.commons.lib;

/**
 * Protobuf type {@code OrderGetRedPacketRequest}
 */
public  final class OrderGetRedPacketRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OrderGetRedPacketRequest)
    OrderGetRedPacketRequestOrBuilder {
  // Use OrderGetRedPacketRequest.newBuilder() to construct.
  private OrderGetRedPacketRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderGetRedPacketRequest() {
    redPacketId_ = "";
    redPacketAmount_ = "";
    redPacketName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private OrderGetRedPacketRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            redPacketId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            redPacketAmount_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            redPacketName_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.smart.website.commons.lib.RedPacketProto.internal_static_OrderGetRedPacketRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.smart.website.commons.lib.RedPacketProto.internal_static_OrderGetRedPacketRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    org.smart.website.commons.lib.OrderGetRedPacketRequest.class, org.smart.website.commons.lib.OrderGetRedPacketRequest.Builder.class);
  }

  public static final int REDPACKETID_FIELD_NUMBER = 1;
  private volatile java.lang.Object redPacketId_;
  /**
   * <code>string redPacketId = 1;</code>
   */
  public java.lang.String getRedPacketId() {
    java.lang.Object ref = redPacketId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      redPacketId_ = s;
      return s;
    }
  }
  /**
   * <code>string redPacketId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRedPacketIdBytes() {
    java.lang.Object ref = redPacketId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      redPacketId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REDPACKETAMOUNT_FIELD_NUMBER = 2;
  private volatile java.lang.Object redPacketAmount_;
  /**
   * <code>string redPacketAmount = 2;</code>
   */
  public java.lang.String getRedPacketAmount() {
    java.lang.Object ref = redPacketAmount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      redPacketAmount_ = s;
      return s;
    }
  }
  /**
   * <code>string redPacketAmount = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRedPacketAmountBytes() {
    java.lang.Object ref = redPacketAmount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      redPacketAmount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REDPACKETNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object redPacketName_;
  /**
   * <code>string redPacketName = 3;</code>
   */
  public java.lang.String getRedPacketName() {
    java.lang.Object ref = redPacketName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      redPacketName_ = s;
      return s;
    }
  }
  /**
   * <code>string redPacketName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRedPacketNameBytes() {
    java.lang.Object ref = redPacketName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      redPacketName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRedPacketIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, redPacketId_);
    }
    if (!getRedPacketAmountBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, redPacketAmount_);
    }
    if (!getRedPacketNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, redPacketName_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRedPacketIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, redPacketId_);
    }
    if (!getRedPacketAmountBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, redPacketAmount_);
    }
    if (!getRedPacketNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, redPacketName_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof org.smart.website.commons.lib.OrderGetRedPacketRequest)) {
      return super.equals(obj);
    }
    org.smart.website.commons.lib.OrderGetRedPacketRequest other = (org.smart.website.commons.lib.OrderGetRedPacketRequest) obj;

    boolean result = true;
    result = result && getRedPacketId()
        .equals(other.getRedPacketId());
    result = result && getRedPacketAmount()
        .equals(other.getRedPacketAmount());
    result = result && getRedPacketName()
        .equals(other.getRedPacketName());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REDPACKETID_FIELD_NUMBER;
    hash = (53 * hash) + getRedPacketId().hashCode();
    hash = (37 * hash) + REDPACKETAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getRedPacketAmount().hashCode();
    hash = (37 * hash) + REDPACKETNAME_FIELD_NUMBER;
    hash = (53 * hash) + getRedPacketName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.smart.website.commons.lib.OrderGetRedPacketRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static org.smart.website.commons.lib.OrderGetRedPacketRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static org.smart.website.commons.lib.OrderGetRedPacketRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static org.smart.website.commons.lib.OrderGetRedPacketRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static org.smart.website.commons.lib.OrderGetRedPacketRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static org.smart.website.commons.lib.OrderGetRedPacketRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.smart.website.commons.lib.OrderGetRedPacketRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.smart.website.commons.lib.OrderGetRedPacketRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.smart.website.commons.lib.OrderGetRedPacketRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static org.smart.website.commons.lib.OrderGetRedPacketRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(org.smart.website.commons.lib.OrderGetRedPacketRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code OrderGetRedPacketRequest}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:OrderGetRedPacketRequest)
          org.smart.website.commons.lib.OrderGetRedPacketRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return org.smart.website.commons.lib.RedPacketProto.internal_static_OrderGetRedPacketRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return org.smart.website.commons.lib.RedPacketProto.internal_static_OrderGetRedPacketRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      org.smart.website.commons.lib.OrderGetRedPacketRequest.class, org.smart.website.commons.lib.OrderGetRedPacketRequest.Builder.class);
    }

    // Construct using org.smart.website.commons.lib.OrderGetRedPacketRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      redPacketId_ = "";

      redPacketAmount_ = "";

      redPacketName_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return org.smart.website.commons.lib.RedPacketProto.internal_static_OrderGetRedPacketRequest_descriptor;
    }

    public org.smart.website.commons.lib.OrderGetRedPacketRequest getDefaultInstanceForType() {
      return org.smart.website.commons.lib.OrderGetRedPacketRequest.getDefaultInstance();
    }

    public org.smart.website.commons.lib.OrderGetRedPacketRequest build() {
      org.smart.website.commons.lib.OrderGetRedPacketRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.smart.website.commons.lib.OrderGetRedPacketRequest buildPartial() {
      org.smart.website.commons.lib.OrderGetRedPacketRequest result = new org.smart.website.commons.lib.OrderGetRedPacketRequest(this);
      result.redPacketId_ = redPacketId_;
      result.redPacketAmount_ = redPacketAmount_;
      result.redPacketName_ = redPacketName_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.smart.website.commons.lib.OrderGetRedPacketRequest) {
        return mergeFrom((org.smart.website.commons.lib.OrderGetRedPacketRequest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.smart.website.commons.lib.OrderGetRedPacketRequest other) {
      if (other == org.smart.website.commons.lib.OrderGetRedPacketRequest.getDefaultInstance()) return this;
      if (!other.getRedPacketId().isEmpty()) {
        redPacketId_ = other.redPacketId_;
        onChanged();
      }
      if (!other.getRedPacketAmount().isEmpty()) {
        redPacketAmount_ = other.redPacketAmount_;
        onChanged();
      }
      if (!other.getRedPacketName().isEmpty()) {
        redPacketName_ = other.redPacketName_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.smart.website.commons.lib.OrderGetRedPacketRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.smart.website.commons.lib.OrderGetRedPacketRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object redPacketId_ = "";
    /**
     * <code>string redPacketId = 1;</code>
     */
    public java.lang.String getRedPacketId() {
      java.lang.Object ref = redPacketId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        redPacketId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string redPacketId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRedPacketIdBytes() {
      java.lang.Object ref = redPacketId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redPacketId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string redPacketId = 1;</code>
     */
    public Builder setRedPacketId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      redPacketId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string redPacketId = 1;</code>
     */
    public Builder clearRedPacketId() {
      
      redPacketId_ = getDefaultInstance().getRedPacketId();
      onChanged();
      return this;
    }
    /**
     * <code>string redPacketId = 1;</code>
     */
    public Builder setRedPacketIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      redPacketId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object redPacketAmount_ = "";
    /**
     * <code>string redPacketAmount = 2;</code>
     */
    public java.lang.String getRedPacketAmount() {
      java.lang.Object ref = redPacketAmount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        redPacketAmount_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string redPacketAmount = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRedPacketAmountBytes() {
      java.lang.Object ref = redPacketAmount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redPacketAmount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string redPacketAmount = 2;</code>
     */
    public Builder setRedPacketAmount(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      redPacketAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string redPacketAmount = 2;</code>
     */
    public Builder clearRedPacketAmount() {
      
      redPacketAmount_ = getDefaultInstance().getRedPacketAmount();
      onChanged();
      return this;
    }
    /**
     * <code>string redPacketAmount = 2;</code>
     */
    public Builder setRedPacketAmountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      redPacketAmount_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object redPacketName_ = "";
    /**
     * <code>string redPacketName = 3;</code>
     */
    public java.lang.String getRedPacketName() {
      java.lang.Object ref = redPacketName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        redPacketName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string redPacketName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRedPacketNameBytes() {
      java.lang.Object ref = redPacketName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redPacketName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string redPacketName = 3;</code>
     */
    public Builder setRedPacketName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      redPacketName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string redPacketName = 3;</code>
     */
    public Builder clearRedPacketName() {
      
      redPacketName_ = getDefaultInstance().getRedPacketName();
      onChanged();
      return this;
    }
    /**
     * <code>string redPacketName = 3;</code>
     */
    public Builder setRedPacketNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      redPacketName_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:OrderGetRedPacketRequest)
  }

  // @@protoc_insertion_point(class_scope:OrderGetRedPacketRequest)
  private static final org.smart.website.commons.lib.OrderGetRedPacketRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.smart.website.commons.lib.OrderGetRedPacketRequest();
  }

  public static org.smart.website.commons.lib.OrderGetRedPacketRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderGetRedPacketRequest>
      PARSER = new com.google.protobuf.AbstractParser<OrderGetRedPacketRequest>() {
    public OrderGetRedPacketRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderGetRedPacketRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderGetRedPacketRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderGetRedPacketRequest> getParserForType() {
    return PARSER;
  }

  public org.smart.website.commons.lib.OrderGetRedPacketRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

