// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package org.smart.website.commons.lib;

/**
 * Protobuf type {@code OrderGetProductReply}
 */
public  final class OrderGetProductReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OrderGetProductReply)
    OrderGetProductReplyOrBuilder {
  public static final int PRODUCTID_FIELD_NUMBER = 1;
  public static final int PRODUCTNAME_FIELD_NUMBER = 2;
  public static final int PRODUCTPIC_FIELD_NUMBER = 3;
  public static final int PRODUCTPRICE_FIELD_NUMBER = 4;
  public static final int PRODUCTSKUCODE_FIELD_NUMBER = 5;
  public static final int PRODUCTSKUID_FIELD_NUMBER = 6;
  public static final int PRODUCTCATEGORYID_FIELD_NUMBER = 7;
  public static final int PRODUCTSALESATTRIBUTE_FIELD_NUMBER = 8;
  public static final int PRODUCTATTRIBUTES_FIELD_NUMBER = 9;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:OrderGetProductReply)
  private static final org.smart.website.commons.lib.OrderGetProductReply DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<OrderGetProductReply>
      PARSER = new com.google.protobuf.AbstractParser<OrderGetProductReply>() {
    public OrderGetProductReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderGetProductReply(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new org.smart.website.commons.lib.OrderGetProductReply();
  }

  private volatile java.lang.Object productId_;
  private volatile java.lang.Object productName_;
  private volatile java.lang.Object productPic_;
  private volatile java.lang.Object productPrice_;
  private volatile java.lang.Object productSkuCode_;
  private volatile java.lang.Object productSkuId_;
  private volatile java.lang.Object productCategoryId_;
  private volatile java.lang.Object productSalesAttribute_;
  private volatile java.lang.Object productAttributes_;
  private byte memoizedIsInitialized = -1;
  // Use OrderGetProductReply.newBuilder() to construct.
  private OrderGetProductReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderGetProductReply() {
    productId_ = "";
    productName_ = "";
    productPic_ = "";
    productPrice_ = "";
    productSkuCode_ = "";
    productSkuId_ = "";
    productCategoryId_ = "";
    productSalesAttribute_ = "";
    productAttributes_ = "";
  }
  private OrderGetProductReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            productId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            productName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            productPic_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            productPrice_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            productSkuCode_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            productSkuId_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            productCategoryId_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            productSalesAttribute_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            productAttributes_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.smart.website.commons.lib.ProductProto.internal_static_OrderGetProductReply_descriptor;
  }

  public static org.smart.website.commons.lib.OrderGetProductReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static org.smart.website.commons.lib.OrderGetProductReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static org.smart.website.commons.lib.OrderGetProductReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static org.smart.website.commons.lib.OrderGetProductReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static org.smart.website.commons.lib.OrderGetProductReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static org.smart.website.commons.lib.OrderGetProductReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.smart.website.commons.lib.OrderGetProductReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.smart.website.commons.lib.OrderGetProductReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.smart.website.commons.lib.OrderGetProductReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static org.smart.website.commons.lib.OrderGetProductReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(org.smart.website.commons.lib.OrderGetProductReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static org.smart.website.commons.lib.OrderGetProductReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<OrderGetProductReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.smart.website.commons.lib.ProductProto.internal_static_OrderGetProductReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.smart.website.commons.lib.OrderGetProductReply.class, org.smart.website.commons.lib.OrderGetProductReply.Builder.class);
  }

  /**
   * <code>string productId = 1;</code>
   */
  public java.lang.String getProductId() {
    java.lang.Object ref = productId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productId_ = s;
      return s;
    }
  }

  /**
   * <code>string productId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getProductIdBytes() {
    java.lang.Object ref = productId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string productName = 2;</code>
   */
  public java.lang.String getProductName() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productName_ = s;
      return s;
    }
  }

  /**
   * <code>string productName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string productPic = 3;</code>
   */
  public java.lang.String getProductPic() {
    java.lang.Object ref = productPic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productPic_ = s;
      return s;
    }
  }

  /**
   * <code>string productPic = 3;</code>
   */
  public com.google.protobuf.ByteString
      getProductPicBytes() {
    java.lang.Object ref = productPic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productPic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string productPrice = 4;</code>
   */
  public java.lang.String getProductPrice() {
    java.lang.Object ref = productPrice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productPrice_ = s;
      return s;
    }
  }

  /**
   * <code>string productPrice = 4;</code>
   */
  public com.google.protobuf.ByteString
      getProductPriceBytes() {
    java.lang.Object ref = productPrice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productPrice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string productSkuCode = 5;</code>
   */
  public java.lang.String getProductSkuCode() {
    java.lang.Object ref = productSkuCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productSkuCode_ = s;
      return s;
    }
  }

  /**
   * <code>string productSkuCode = 5;</code>
   */
  public com.google.protobuf.ByteString
      getProductSkuCodeBytes() {
    java.lang.Object ref = productSkuCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productSkuCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string productSkuId = 6;</code>
   */
  public java.lang.String getProductSkuId() {
    java.lang.Object ref = productSkuId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productSkuId_ = s;
      return s;
    }
  }

  /**
   * <code>string productSkuId = 6;</code>
   */
  public com.google.protobuf.ByteString
      getProductSkuIdBytes() {
    java.lang.Object ref = productSkuId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productSkuId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string productCategoryId = 7;</code>
   */
  public java.lang.String getProductCategoryId() {
    java.lang.Object ref = productCategoryId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productCategoryId_ = s;
      return s;
    }
  }

  /**
   * <code>string productCategoryId = 7;</code>
   */
  public com.google.protobuf.ByteString
      getProductCategoryIdBytes() {
    java.lang.Object ref = productCategoryId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productCategoryId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string productSalesAttribute = 8;</code>
   */
  public java.lang.String getProductSalesAttribute() {
    java.lang.Object ref = productSalesAttribute_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productSalesAttribute_ = s;
      return s;
    }
  }

  /**
   * <code>string productSalesAttribute = 8;</code>
   */
  public com.google.protobuf.ByteString
      getProductSalesAttributeBytes() {
    java.lang.Object ref = productSalesAttribute_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productSalesAttribute_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string productAttributes = 9;</code>
   */
  public java.lang.String getProductAttributes() {
    java.lang.Object ref = productAttributes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productAttributes_ = s;
      return s;
    }
  }

  /**
   * <code>string productAttributes = 9;</code>
   */
  public com.google.protobuf.ByteString
      getProductAttributesBytes() {
    java.lang.Object ref = productAttributes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productAttributes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getProductIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, productId_);
    }
    if (!getProductNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productName_);
    }
    if (!getProductPicBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, productPic_);
    }
    if (!getProductPriceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, productPrice_);
    }
    if (!getProductSkuCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, productSkuCode_);
    }
    if (!getProductSkuIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, productSkuId_);
    }
    if (!getProductCategoryIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, productCategoryId_);
    }
    if (!getProductSalesAttributeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, productSalesAttribute_);
    }
    if (!getProductAttributesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, productAttributes_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getProductIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, productId_);
    }
    if (!getProductNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productName_);
    }
    if (!getProductPicBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, productPic_);
    }
    if (!getProductPriceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, productPrice_);
    }
    if (!getProductSkuCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, productSkuCode_);
    }
    if (!getProductSkuIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, productSkuId_);
    }
    if (!getProductCategoryIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, productCategoryId_);
    }
    if (!getProductSalesAttributeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, productSalesAttribute_);
    }
    if (!getProductAttributesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, productAttributes_);
    }
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.smart.website.commons.lib.OrderGetProductReply)) {
      return super.equals(obj);
    }
    org.smart.website.commons.lib.OrderGetProductReply other = (org.smart.website.commons.lib.OrderGetProductReply) obj;

    boolean result = true;
    result = result && getProductId()
        .equals(other.getProductId());
    result = result && getProductName()
        .equals(other.getProductName());
    result = result && getProductPic()
        .equals(other.getProductPic());
    result = result && getProductPrice()
        .equals(other.getProductPrice());
    result = result && getProductSkuCode()
        .equals(other.getProductSkuCode());
    result = result && getProductSkuId()
        .equals(other.getProductSkuId());
    result = result && getProductCategoryId()
        .equals(other.getProductCategoryId());
    result = result && getProductSalesAttribute()
        .equals(other.getProductSalesAttribute());
    result = result && getProductAttributes()
        .equals(other.getProductAttributes());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
    hash = (53 * hash) + getProductId().hashCode();
    hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getProductName().hashCode();
    hash = (37 * hash) + PRODUCTPIC_FIELD_NUMBER;
    hash = (53 * hash) + getProductPic().hashCode();
    hash = (37 * hash) + PRODUCTPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getProductPrice().hashCode();
    hash = (37 * hash) + PRODUCTSKUCODE_FIELD_NUMBER;
    hash = (53 * hash) + getProductSkuCode().hashCode();
    hash = (37 * hash) + PRODUCTSKUID_FIELD_NUMBER;
    hash = (53 * hash) + getProductSkuId().hashCode();
    hash = (37 * hash) + PRODUCTCATEGORYID_FIELD_NUMBER;
    hash = (53 * hash) + getProductCategoryId().hashCode();
    hash = (37 * hash) + PRODUCTSALESATTRIBUTE_FIELD_NUMBER;
    hash = (53 * hash) + getProductSalesAttribute().hashCode();
    hash = (37 * hash) + PRODUCTATTRIBUTES_FIELD_NUMBER;
    hash = (53 * hash) + getProductAttributes().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public Builder newBuilderForType() { return newBuilder(); }

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderGetProductReply> getParserForType() {
    return PARSER;
  }

  public org.smart.website.commons.lib.OrderGetProductReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code OrderGetProductReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OrderGetProductReply)
      org.smart.website.commons.lib.OrderGetProductReplyOrBuilder {
    private java.lang.Object productId_ = "";
    private java.lang.Object productName_ = "";
    private java.lang.Object productPic_ = "";
    private java.lang.Object productPrice_ = "";
    private java.lang.Object productSkuCode_ = "";
    private java.lang.Object productSkuId_ = "";
    private java.lang.Object productCategoryId_ = "";
    private java.lang.Object productSalesAttribute_ = "";
    private java.lang.Object productAttributes_ = "";

    // Construct using org.smart.website.commons.lib.OrderGetProductReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.smart.website.commons.lib.ProductProto.internal_static_OrderGetProductReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.smart.website.commons.lib.ProductProto.internal_static_OrderGetProductReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.smart.website.commons.lib.OrderGetProductReply.class, org.smart.website.commons.lib.OrderGetProductReply.Builder.class);
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

    public Builder clear() {
      super.clear();
      productId_ = "";

      productName_ = "";

      productPic_ = "";

      productPrice_ = "";

      productSkuCode_ = "";

      productSkuId_ = "";

      productCategoryId_ = "";

      productSalesAttribute_ = "";

      productAttributes_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.smart.website.commons.lib.ProductProto.internal_static_OrderGetProductReply_descriptor;
    }

    public org.smart.website.commons.lib.OrderGetProductReply getDefaultInstanceForType() {
      return org.smart.website.commons.lib.OrderGetProductReply.getDefaultInstance();
    }

    public org.smart.website.commons.lib.OrderGetProductReply build() {
      org.smart.website.commons.lib.OrderGetProductReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.smart.website.commons.lib.OrderGetProductReply buildPartial() {
      org.smart.website.commons.lib.OrderGetProductReply result = new org.smart.website.commons.lib.OrderGetProductReply(this);
      result.productId_ = productId_;
      result.productName_ = productName_;
      result.productPic_ = productPic_;
      result.productPrice_ = productPrice_;
      result.productSkuCode_ = productSkuCode_;
      result.productSkuId_ = productSkuId_;
      result.productCategoryId_ = productCategoryId_;
      result.productSalesAttribute_ = productSalesAttribute_;
      result.productAttributes_ = productAttributes_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }

    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }

    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.smart.website.commons.lib.OrderGetProductReply) {
        return mergeFrom((org.smart.website.commons.lib.OrderGetProductReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.smart.website.commons.lib.OrderGetProductReply other) {
      if (other == org.smart.website.commons.lib.OrderGetProductReply.getDefaultInstance()) return this;
      if (!other.getProductId().isEmpty()) {
        productId_ = other.productId_;
        onChanged();
      }
      if (!other.getProductName().isEmpty()) {
        productName_ = other.productName_;
        onChanged();
      }
      if (!other.getProductPic().isEmpty()) {
        productPic_ = other.productPic_;
        onChanged();
      }
      if (!other.getProductPrice().isEmpty()) {
        productPrice_ = other.productPrice_;
        onChanged();
      }
      if (!other.getProductSkuCode().isEmpty()) {
        productSkuCode_ = other.productSkuCode_;
        onChanged();
      }
      if (!other.getProductSkuId().isEmpty()) {
        productSkuId_ = other.productSkuId_;
        onChanged();
      }
      if (!other.getProductCategoryId().isEmpty()) {
        productCategoryId_ = other.productCategoryId_;
        onChanged();
      }
      if (!other.getProductSalesAttribute().isEmpty()) {
        productSalesAttribute_ = other.productSalesAttribute_;
        onChanged();
      }
      if (!other.getProductAttributes().isEmpty()) {
        productAttributes_ = other.productAttributes_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.smart.website.commons.lib.OrderGetProductReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.smart.website.commons.lib.OrderGetProductReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    /**
     * <code>string productId = 1;</code>
     */
    public java.lang.String getProductId() {
      java.lang.Object ref = productId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string productId = 1;</code>
     */
    public Builder setProductId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      productId_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = productId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string productId = 1;</code>
     */
    public Builder setProductIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      productId_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productId = 1;</code>
     */
    public Builder clearProductId() {

      productId_ = getDefaultInstance().getProductId();
      onChanged();
      return this;
    }

    /**
     * <code>string productName = 2;</code>
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string productName = 2;</code>
     */
    public Builder setProductName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      productName_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string productName = 2;</code>
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      productName_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productName = 2;</code>
     */
    public Builder clearProductName() {

      productName_ = getDefaultInstance().getProductName();
      onChanged();
      return this;
    }

    /**
     * <code>string productPic = 3;</code>
     */
    public java.lang.String getProductPic() {
      java.lang.Object ref = productPic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productPic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string productPic = 3;</code>
     */
    public Builder setProductPic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      productPic_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productPic = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProductPicBytes() {
      java.lang.Object ref = productPic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productPic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string productPic = 3;</code>
     */
    public Builder setProductPicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      productPic_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productPic = 3;</code>
     */
    public Builder clearProductPic() {

      productPic_ = getDefaultInstance().getProductPic();
      onChanged();
      return this;
    }

    /**
     * <code>string productPrice = 4;</code>
     */
    public java.lang.String getProductPrice() {
      java.lang.Object ref = productPrice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productPrice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string productPrice = 4;</code>
     */
    public Builder setProductPrice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      productPrice_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productPrice = 4;</code>
     */
    public com.google.protobuf.ByteString
        getProductPriceBytes() {
      java.lang.Object ref = productPrice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string productPrice = 4;</code>
     */
    public Builder setProductPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      productPrice_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productPrice = 4;</code>
     */
    public Builder clearProductPrice() {

      productPrice_ = getDefaultInstance().getProductPrice();
      onChanged();
      return this;
    }

    /**
     * <code>string productSkuCode = 5;</code>
     */
    public java.lang.String getProductSkuCode() {
      java.lang.Object ref = productSkuCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productSkuCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string productSkuCode = 5;</code>
     */
    public Builder setProductSkuCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      productSkuCode_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productSkuCode = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProductSkuCodeBytes() {
      java.lang.Object ref = productSkuCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productSkuCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string productSkuCode = 5;</code>
     */
    public Builder setProductSkuCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      productSkuCode_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productSkuCode = 5;</code>
     */
    public Builder clearProductSkuCode() {

      productSkuCode_ = getDefaultInstance().getProductSkuCode();
      onChanged();
      return this;
    }

    /**
     * <code>string productSkuId = 6;</code>
     */
    public java.lang.String getProductSkuId() {
      java.lang.Object ref = productSkuId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productSkuId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string productSkuId = 6;</code>
     */
    public Builder setProductSkuId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      productSkuId_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productSkuId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getProductSkuIdBytes() {
      java.lang.Object ref = productSkuId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productSkuId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string productSkuId = 6;</code>
     */
    public Builder setProductSkuIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      productSkuId_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productSkuId = 6;</code>
     */
    public Builder clearProductSkuId() {

      productSkuId_ = getDefaultInstance().getProductSkuId();
      onChanged();
      return this;
    }

    /**
     * <code>string productCategoryId = 7;</code>
     */
    public java.lang.String getProductCategoryId() {
      java.lang.Object ref = productCategoryId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productCategoryId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string productCategoryId = 7;</code>
     */
    public Builder setProductCategoryId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      productCategoryId_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productCategoryId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getProductCategoryIdBytes() {
      java.lang.Object ref = productCategoryId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productCategoryId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string productCategoryId = 7;</code>
     */
    public Builder setProductCategoryIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      productCategoryId_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productCategoryId = 7;</code>
     */
    public Builder clearProductCategoryId() {

      productCategoryId_ = getDefaultInstance().getProductCategoryId();
      onChanged();
      return this;
    }

    /**
     * <code>string productSalesAttribute = 8;</code>
     */
    public java.lang.String getProductSalesAttribute() {
      java.lang.Object ref = productSalesAttribute_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productSalesAttribute_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string productSalesAttribute = 8;</code>
     */
    public Builder setProductSalesAttribute(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      productSalesAttribute_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productSalesAttribute = 8;</code>
     */
    public com.google.protobuf.ByteString
        getProductSalesAttributeBytes() {
      java.lang.Object ref = productSalesAttribute_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productSalesAttribute_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string productSalesAttribute = 8;</code>
     */
    public Builder setProductSalesAttributeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      productSalesAttribute_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productSalesAttribute = 8;</code>
     */
    public Builder clearProductSalesAttribute() {

      productSalesAttribute_ = getDefaultInstance().getProductSalesAttribute();
      onChanged();
      return this;
    }

    /**
     * <code>string productAttributes = 9;</code>
     */
    public java.lang.String getProductAttributes() {
      java.lang.Object ref = productAttributes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productAttributes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string productAttributes = 9;</code>
     */
    public Builder setProductAttributes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      productAttributes_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productAttributes = 9;</code>
     */
    public com.google.protobuf.ByteString
        getProductAttributesBytes() {
      java.lang.Object ref = productAttributes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productAttributes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string productAttributes = 9;</code>
     */
    public Builder setProductAttributesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      productAttributes_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string productAttributes = 9;</code>
     */
    public Builder clearProductAttributes() {

      productAttributes_ = getDefaultInstance().getProductAttributes();
      onChanged();
      return this;
    }

    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:OrderGetProductReply)
  }

}

