// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package org.smart.website.commons.lib;

public interface OrderGetUserReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderGetUserReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string address = 2;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string username = 3;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 3;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string realname = 4;</code>
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 4;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();

  /**
   * <code>string role = 5;</code>
   */
  java.lang.String getRole();
  /**
   * <code>string role = 5;</code>
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>string phone = 6;</code>
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 6;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string memberName = 7;</code>
   */
  java.lang.String getMemberName();
  /**
   * <code>string memberName = 7;</code>
   */
  com.google.protobuf.ByteString
      getMemberNameBytes();

  /**
   * <code>string memberLevel = 8;</code>
   */
  java.lang.String getMemberLevel();
  /**
   * <code>string memberLevel = 8;</code>
   */
  com.google.protobuf.ByteString
      getMemberLevelBytes();

  /**
   * <code>string integration = 9;</code>
   */
  java.lang.String getIntegration();
  /**
   * <code>string integration = 9;</code>
   */
  com.google.protobuf.ByteString
      getIntegrationBytes();
}
