// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package org.smart.website.commons.lib;

public interface OrderGetProductReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderGetProductReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productId = 1;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>string productId = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>string productName = 2;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>string productPic = 3;</code>
   */
  java.lang.String getProductPic();
  /**
   * <code>string productPic = 3;</code>
   */
  com.google.protobuf.ByteString
      getProductPicBytes();

  /**
   * <code>string productPrice = 4;</code>
   */
  java.lang.String getProductPrice();
  /**
   * <code>string productPrice = 4;</code>
   */
  com.google.protobuf.ByteString
      getProductPriceBytes();

  /**
   * <code>string productSkuCode = 5;</code>
   */
  java.lang.String getProductSkuCode();
  /**
   * <code>string productSkuCode = 5;</code>
   */
  com.google.protobuf.ByteString
      getProductSkuCodeBytes();

  /**
   * <code>string productSkuId = 6;</code>
   */
  java.lang.String getProductSkuId();
  /**
   * <code>string productSkuId = 6;</code>
   */
  com.google.protobuf.ByteString
      getProductSkuIdBytes();

  /**
   * <code>string productCategoryId = 7;</code>
   */
  java.lang.String getProductCategoryId();
  /**
   * <code>string productCategoryId = 7;</code>
   */
  com.google.protobuf.ByteString
      getProductCategoryIdBytes();

  /**
   * <code>string productSalesAttribute = 8;</code>
   */
  java.lang.String getProductSalesAttribute();
  /**
   * <code>string productSalesAttribute = 8;</code>
   */
  com.google.protobuf.ByteString
      getProductSalesAttributeBytes();

  /**
   * <code>string productAttributes = 9;</code>
   */
  java.lang.String getProductAttributes();
  /**
   * <code>string productAttributes = 9;</code>
   */
  com.google.protobuf.ByteString
      getProductAttributesBytes();
}
