// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Promotion.proto

package org.smart.website.commons.lib;

public final class PromotionProto {
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderToPromotionRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderToPromotionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderGetPromotionReply_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderGetPromotionReply_fieldAccessorTable;
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\017Promotion.proto\"<\n\027OrderToPromotionReq" +
      "uest\022\016\n\006userId\030\001 \001(\t\022\021\n\tproductId\030\002 \001(\t\"" +
      "]\n\026OrderGetPromotionReply\022\023\n\013PromotionId" +
      "\030\001 \001(\t\022\027\n\017PromotionAmount\030\002 \001(\t\022\025\n\rPromo" +
      "tionName\030\003 \001(\t2f\n\030OrderGetPromotionMessa" +
      "ge\022J\n\023GetOrderToPromotion\022\030.OrderToPromo" +
      "tionRequest\032\027.OrderGetPromotionReply\"\000B1" +
      "\n\035org.smart.website.commons.libB\016Promoti" +
      "onProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OrderToPromotionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderToPromotionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderToPromotionRequest_descriptor,
        new java.lang.String[] { "UserId", "ProductId", });
    internal_static_OrderGetPromotionReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OrderGetPromotionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderGetPromotionReply_descriptor,
        new java.lang.String[] { "PromotionId", "PromotionAmount", "PromotionName", });
  }
  private PromotionProto() {}

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }

  // @@protoc_insertion_point(outer_class_scope)
}
