// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RedPacket.proto

package org.smart.website.commons.lib;

public final class RedPacketProto {
  private RedPacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderToRedPacketRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderToRedPacketRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderGetRedPacketRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderGetRedPacketRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017RedPacket.proto\"<\n\027OrderToRedPacketReq" +
              "uest\022\016\n\006userId\030\001 \001(\t\022\021\n\tproductId\030\002 \001(\t\"" +
              "_\n\030OrderGetRedPacketRequest\022\023\n\013redPacket" +
              "Id\030\001 \001(\t\022\027\n\017redPacketAmount\030\002 \001(\t\022\025\n\rred" +
              "PacketName\030\003 \001(\t2h\n\030OrderGetRedPacketMes" +
              "sage\022L\n\023GetOrderToRedPacket\022\030.OrderToRed" +
              "PacketRequest\032\031.OrderGetRedPacketRequest" +
              "\"\000B1\n\035org.smart.website.commons.libB\016Red" +
              "PacketProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OrderToRedPacketRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderToRedPacketRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderToRedPacketRequest_descriptor,
        new java.lang.String[] { "UserId", "ProductId", });
    internal_static_OrderGetRedPacketRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OrderGetRedPacketRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderGetRedPacketRequest_descriptor,
        new java.lang.String[] { "RedPacketId", "RedPacketAmount", "RedPacketName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
