// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package org.smart.website.commons.lib;

public interface RedPackGetReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RedPackGetReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string phone = 3;</code>
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 3;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();
}
