// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package org.smart.website.commons.lib;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderGetUserReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderGetUserReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderToUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderToUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductGetUserReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductGetUserReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductToRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductToRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CouponToRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CouponToRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CouponGetReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CouponGetReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RedPackToRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RedPackToRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RedPackGetReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RedPackGetReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommentToUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommentToUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommentGetUserReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommentGetUserReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CouponToUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CouponToUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CouponGetUserReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CouponGetUserReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RedPacketToUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RedPacketToUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RedPacketGetUserReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RedPacketGetUserReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\"\263\001\n\021OrderGetUserReply\022\016\n\006us" +
      "erId\030\001 \001(\t\022\017\n\007address\030\002 \001(\t\022\020\n\010username\030" +
      "\003 \001(\t\022\020\n\010realname\030\004 \001(\t\022\014\n\004role\030\005 \001(\t\022\r\n" +
      "\005phone\030\006 \001(\t\022\022\n\nmemberName\030\007 \001(\t\022\023\n\013memb" +
      "erLevel\030\010 \001(\t\022\023\n\013integration\030\t \001(\t\"I\n\022Or" +
      "derToUserRequest\022\016\n\006userId\030\001 \001(\t\022\023\n\013inte" +
      "gration\030\002 \001(\t\022\016\n\006growth\030\003 \001(\t\"%\n\023Product" +
      "GetUserReply\022\016\n\006userId\030\001 \001(\t\"\"\n\020ProductT" +
      "oRequest\022\016\n\006userId\030\001 \001(\t\"!\n\017CouponToRequ" +
      "est\022\016\n\006userId\030\001 \001(\t\"P\n\016CouponGetReply\022\016\n",
      "\006userId\030\001 \001(\t\022\020\n\010username\030\002 \001(\t\022\r\n\005phone" +
      "\030\003 \001(\t\022\r\n\005level\030\004 \001(\t\"\"\n\020RedPackToReques" +
      "t\022\016\n\006userId\030\001 \001(\t\"B\n\017RedPackGetReply\022\016\n\006" +
      "userId\030\001 \001(\t\022\020\n\010username\030\002 \001(\t\022\r\n\005phone\030" +
      "\003 \001(\t\"&\n\024CommentToUserRequest\022\016\n\006userId\030" +
      "\001 \001(\t\"E\n\023CommentGetUserReply\022\016\n\006userId\030\001" +
      " \001(\t\022\020\n\010username\030\002 \001(\t\022\014\n\004icon\030\003 \001(\t\"%\n\023" +
      "CouponToUserRequest\022\016\n\006userId\030\001 \001(\t\"6\n\022C" +
      "ouponGetUserReply\022\016\n\006userId\030\001 \001(\t\022\020\n\010use" +
      "rname\030\002 \001(\t\"(\n\026RedPacketToUserRequest\022\016\n",
      "\006userId\030\001 \001(\t\"9\n\025RedPacketGetUserReply\022\016" +
      "\n\006userId\030\001 \001(\t\022\020\n\010username\030\002 \001(\t2R\n\023Orde" +
      "rGetUserMessage\022;\n\016GetOrderToUser\022\023.Orde" +
      "rToUserRequest\032\022.OrderGetUserReply\"\0002U\n\025" +
      "ProductGetUserMessage\022<\n\017GetProductToUsr" +
      "\022\021.ProductToRequest\032\024.ProductGetUserRepl" +
      "y\"\0002N\n\024CouponGetUserMessage\0226\n\017GetCoupon" +
      "ToUser\022\020.CouponToRequest\032\017.CouponGetRepl" +
      "y\"\0002V\n\027RedPacketGetUserMessage\022;\n\022GetRed" +
      "PacketToUser\022\021.RedPackToRequest\032\020.RedPac",
      "kGetReply\"\0002Z\n\025CommentGetUserMessage\022A\n\020" +
      "GetCommentToUser\022\025.CommentToUserRequest\032" +
      "\024.CommentGetUserReply\"\0002]\n\026RedPacketGetU" +
      "serPacket\022C\n\022GetRedPacketToUser\022\025.Commen" +
      "tToUserRequest\032\024.CommentGetUserReply\"\000B," +
      "\n\035com.smart.website.commons.libB\tUserPro" +
      "toP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OrderGetUserReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderGetUserReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderGetUserReply_descriptor,
        new java.lang.String[] { "UserId", "Address", "Username", "Realname", "Role", "Phone", "MemberName", "MemberLevel", "Integration", });
    internal_static_OrderToUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OrderToUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderToUserRequest_descriptor,
        new java.lang.String[] { "UserId", "Integration", "Growth", });
    internal_static_ProductGetUserReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProductGetUserReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductGetUserReply_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_ProductToRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ProductToRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductToRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_CouponToRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CouponToRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CouponToRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_CouponGetReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CouponGetReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CouponGetReply_descriptor,
        new java.lang.String[] { "UserId", "Username", "Phone", "Level", });
    internal_static_RedPackToRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_RedPackToRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RedPackToRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_RedPackGetReply_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_RedPackGetReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RedPackGetReply_descriptor,
        new java.lang.String[] { "UserId", "Username", "Phone", });
    internal_static_CommentToUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_CommentToUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommentToUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_CommentGetUserReply_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_CommentGetUserReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommentGetUserReply_descriptor,
        new java.lang.String[] { "UserId", "Username", "Icon", });
    internal_static_CouponToUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_CouponToUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CouponToUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_CouponGetUserReply_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_CouponGetUserReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CouponGetUserReply_descriptor,
        new java.lang.String[] { "UserId", "Username", });
    internal_static_RedPacketToUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_RedPacketToUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RedPacketToUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_RedPacketGetUserReply_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_RedPacketGetUserReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RedPacketGetUserReply_descriptor,
        new java.lang.String[] { "UserId", "Username", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
