// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Promotion.proto

package org.smart.website.commons.lib;

public interface OrderToPromotionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderToPromotionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string productId = 2;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>string productId = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();
}
