// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Group.proto

package org.smart.website.commons.lib;

public interface OrderGetGroupReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderGetGroupReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string GroupId = 1;</code>
   */
  java.lang.String getGroupId();
  /**
   * <code>string GroupId = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupIdBytes();

  /**
   * <code>string GroupAmount = 2;</code>
   */
  java.lang.String getGroupAmount();
  /**
   * <code>string GroupAmount = 2;</code>
   */
  com.google.protobuf.ByteString
      getGroupAmountBytes();

  /**
   * <code>string GroupName = 3;</code>
   */
  java.lang.String getGroupName();
  /**
   * <code>string GroupName = 3;</code>
   */
  com.google.protobuf.ByteString
      getGroupNameBytes();
}
