// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Market.proto

package org.smart.website.commons.lib;

public interface OrderGetMarketReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderGetMarketReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string MarketId = 1;</code>
   */
  java.lang.String getMarketId();
  /**
   * <code>string MarketId = 1;</code>
   */
  com.google.protobuf.ByteString
      getMarketIdBytes();

  /**
   * <code>string MarketAmount = 2;</code>
   */
  java.lang.String getMarketAmount();
  /**
   * <code>string MarketAmount = 2;</code>
   */
  com.google.protobuf.ByteString
      getMarketAmountBytes();

  /**
   * <code>string MarketName = 3;</code>
   */
  java.lang.String getMarketName();
  /**
   * <code>string MarketName = 3;</code>
   */
  com.google.protobuf.ByteString
      getMarketNameBytes();
}
