spring:
  redis:
    url:
    port: 6379
    password:
  security:
  kafka:
    bootstrap-servers:
    producer:
    consumer:
    client-id:

security:
  oauth2:
    authorization:
      jwt:
j2cache:

  config-location=/j2cache-${spring.profiles.active}.properties