spring:
  profiles: user-domain-config
  jpa:

  cloud:
    stream:
      binders:
        local_kafka:
          type: kafka
          environment:
            spring:
              kafka:
      bindings:
        user_aggregate_input:
          destination: user_aggregation
          binder:  local_kafka
        user_aggregate_output:
          destination: user_aggregation
          binder: local_kafka

  redis:
    url:
    port: 6379
    password:
  security:
  kafka:
    bootstrap-servers:
    producer:
    consumer:
    client-id:

security:
  oauth2:
    authorization:
      jwt:
j2cache:
  config-location:/j2cache-${spring.profiles.active}.properties