axon:
  serializer:
    json
  metrics:
    auto-configuration:
      enabled: true
  distributed:
    jgroups:
      gossip:
        auto-start: true
  eventhandling:
    processors:
spring:
  application:
    name: domain
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/users?Unicode=true&characterEncoding=utf-8
    username: root
    password: yangbiao
    driver-class-name: com.mysql.jdbc.Driver

